orbs:

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: ls

workflows:
  setup:
    jobs:
      - build-and-test
