version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  testing:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-test.yml

  staging:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-test.yml

workflows:
  setup:
    jobs:
      - testing:
          name:
          filters:
            branches:
              only:
                - testing

      - staging:
          name:
          filters:
            branches:
              only:
                - staging