version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            ./config-test > config-test.yml
      - continuation/continue:
          configuration_path: config-test.yml


workflows:
  setup:
    jobs:
      - setup
