orbs:

version: 2.1

commands:
  checkout-cmd:
    steps:
      - checkout
      - run:
          command: |
            mkdir -p ~/.m2/repository/com/crypto
            mv ./lib/pay.zip ~/.m2/repository/com/crypto
            unzip -d ~/.m2/repository/com/crypto  ~/.m2/repository/com/crypto/pay.zip


jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:12.4
        environment:
          POSTGRES_DB: account
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout-cmd
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=snow-li-crypto_circleci-java-test


workflows:
  setup:
    jobs:
      - build-and-test:
          name: bulid
