version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2


commands:
  checkout-cmd:
    steps:
      - checkout


jobs:

  checkout-job:
    docker:
      - image: cimg/openjdk:11.0
    #    working_directory: ~/app/
    steps:
      - checkout-cmd

  testing:
    executor: continuation/default
    #    working_directory: ~/app/
    steps:
      - checkout-cmd
      - continuation/continue:
          configuration_path: /tmp/circleci/.circleci/config-test.yml

  staging:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: ./.circleci/config-staging.yml

  main:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: ./.circleci/config-main.yml

  default:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: ./.circleci/config-default.yml

workflows:
  setup:
    jobs:
      - checkout-job:
          name: checkout

      - testing:
          name: testing-bulid
          requires:
            - checkout
          filters:
            branches:
              only:
                - testing

      - staging:
          name: staging-bulid
          filters:
            branches:
              only:
                - staging

      - main:
          name: main-bulid
          filters:
            branches:
              only:
                - main

      - default:
          name: default-bulid
          filters:
            branches:
              ignore:
                - testing
                - staging
                - main