version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:

  checkout-job:
    working_directory: ~/env/
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

  testing:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ~/env/.circleci/config-test.yml

  staging:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-staging.yml

  main:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-main.yml

  default:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-default.yml

workflows:
  setup:
    jobs:
      - checkout-job

      - testing:
          name: testing-bulid
          filters:
            branches:
              only:
                - testing

      - staging:
          name: staging-bulid
          filters:
            branches:
              only:
                - staging

      - main:
          name: main-bulid
          filters:
            branches:
              only:
                - main

      - default:
          name: default-bulid
          filters:
            branches:
              ignore:
                - testing
                - staging
                - main