orbs:

version: 2.1

commands:
  checkout-cmd:
    steps:
      - checkout

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:12.4
        environment:
          POSTGRES_DB: account
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout-cmd
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar	-Dsonar.login=4576d0302308f75626066d0458f55b7cc1cc148c -Dsonar.projectKey=snow-li-crypto_circleci-java-test   -s .circleci/.circleci.settings.xml


workflows:
  setup:
    jobs:
      - build-and-test:
          name: bulid
