version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  testing:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-test.yml

  staging:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-staging.yml

  main:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-main.yml

  default:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/config-default.yml

workflows:
  setup:
    jobs:
      - testing:
          name: setup
          filters:
            branches:
              only:
                - testing

      - staging:
          name: setup
          filters:
            branches:
              only:
                - staging

      - main:
          name: setup
          filters:
            branches:
              only:
                - main

      - default:
          name: setup
          filters:
            branches:
              ignore:
                - testing
                - staging
                - main